### ISSUE TITLE
Error when running tslint directly

### ISSUE THREAD

**Issue by giggio** [ReactiveX/rxjs-tslint#23]
I am getting errors when running tslint.

This is the error on `rxjsNoStaticObservableMethodsRule.js`:

````
TypeError: Cannot read property 'kind' of undefined
    at Object.isPropertyAccessExpression (C:\p\rabiscos\ngtemp2\Template2\node_modules\tsutils\typeguard\node.js:542:17)
    at isRxjsStaticOperatorCallExpression (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsNoStaticObservableMethodsRule.js:88:18)
    at checkPatchableOperatorUsage (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsNoStaticObservableMethodsRule.js:34:18)
    at visitNodes (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14006:30)
    at Object.forEachChild (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14173:21)
    at checkPatchableOperatorUsage (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsNoStaticObservableMethodsRule.js:35:27)
    at visitNode (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:13997:24)
    at Object.forEachChild (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14229:24)
    at checkPatchableOperatorUsage (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsNoStaticObservableMethodsRule.js:35:27)
    at visitNodes (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14006:30)
````

This is from `rxjsPipeableOperatorsOnlyRule.js`:

````
TypeError: Cannot read property 'kind' of undefined
    at Object.isPropertyAccessExpression (C:\p\rabiscos\ngtemp2\Template2\node_modules\tsutils\typeguard\node.js:542:17)
    at isRxjsInstanceOperatorCallExpression (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsPipeableOperatorsOnlyRule.js:96:18)
    at checkPatchableOperatorUsage (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsPipeableOperatorsOnlyRule.js:33:18)
    at visitNodes (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14006:30)
    at Object.forEachChild (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14173:21)
    at checkPatchableOperatorUsage (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsPipeableOperatorsOnlyRule.js:34:27)
    at visitNode (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:13997:24)
    at Object.forEachChild (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14229:24)
    at checkPatchableOperatorUsage (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\rxjsPipeableOperatorsOnlyRule.js:34:27)
    at visitNodes (C:\p\rabiscos\ngtemp2\Template2\node_modules\rxjs-tslint\node_modules\typescript\lib\typescript.js:14006:30)
````

The errors actually happen several times.

It seems that the error is on this call:

````js
if (!tsutils.isPropertyAccessExpression(node.expression)) {
````

Which is here:
https://github.com/ReactiveX/rxjs-tslint/blob/840f3a96f5f5e7f607efcc4d44eee230b60b4bb7/src/rxjsNoStaticObservableMethodsRule.ts#L95

I am on version 0.1.2.

If you need more information please let me know.

**Comment by mgechev** [comment]
How do you run the linting? As discussed in https://github.com/ReactiveX/rxjs-tslint/issues/21?

**Comment by giggio** [comment]
Yes, `tslint --project .\tsconfig.json`.

**Comment by mgechev** [comment]
Probably, this is creating a mess between different TypeScript versions (i.e. your global TypeScript is not the one used in `node_modules`, etc.), that's why my recommendation was to try:

```
./node_modules/.bin/tslint -p tsconfig.json -c tslint.json
```

For other tslint specific questions, it'd be best if you look at http://github.com/palantir/tslint.
