### ISSUE TITLE
Errors when linting Angular 5 project.

### ISSUE THREAD

**Issue by dgsmith2** [ReactiveX/rxjs-tslint#28]
When I added `rxjs-tslint@^0.1.1` to my Angular 5 project I started getting strange errors.  Both VSC and IDEA reported things such as name collisions on import statements.  Manually running `ng lint` resulted in a series of type errors, such as the following, that ultimately lead to JS running out of heap memory.

```
TypeError: Cannot read property 'kind' of undefined
    at isLabelable (/app/node_modules/tslint/lib/rules/labelPositionRule.js:57:18)
    at cb (/app/node_modules/tslint/lib/rules/labelPositionRule.js:50:52)
    at visitNodes (/app/node_modules/typescript/lib/typescript.js:12699:30)
    at Object.forEachChild (/app/node_modules/typescript/lib/typescript.js:12884:24)
    at cb (/app/node_modules/tslint/lib/rules/labelPositionRule.js:53:19)
    at visitNode (/app/node_modules/typescript/lib/typescript.js:12690:24)
    at Object.forEachChild (/app/node_modules/typescript/lib/typescript.js:12882:21)
    at cb (/app/node_modules/tslint/lib/rules/labelPositionRule.js:53:19)
    at visitNodes (/app/node_modules/typescript/lib/typescript.js:12699:30)
    at Object.forEachChild (/app/node_modules/typescript/lib/typescript.js:12875:24)
```
I think it has to do with `rxjs-tslint` depending on `"typescript": "~2.8.1"` and Angular 5 depending on `"typescript": "2.6.x"`. Folks who encountered this error in other situations ended up altering the version of Typescript they used.

The only solution I could come up with was to remove my dependency on `rxjs-tslint`.  Am I missing an alternative?

**Comment by dgsmith2** [comment]
I guess this "issue" ends up being more of a "heads up" because the README has you install `rxjs-tslint` globally--not meant to be a `devDependency`.

**Comment by mgechev** [comment]
Yes, correct. Please, use the global executable otherwise there could be mismatched dependencies.
