### ISSUE TITLE
rxjs-5-to-6-migrate

### ISSUE THREAD

**Issue by Vishesh-Gupta** [ReactiveX/rxjs-tslint#52]
I have typescript installed as a module using npm but why it cannot still find the module. 

Running the automatic migrations. Please, be patient and wait until the execution completes.
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\GuptaV\AppData\Roaming\npm\node_modules\rxjs-tslint\node_modules\tslint\lib\linter.js:22:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
child_process.js:643
    throw err;
    ^

Error: Command failed: "C:\Users\GuptaV\AppData\Roaming\npm\node_modules\rxjs-tslint\node_modules\.bin\tslint" -c "C:\Users\GuptaV\AppData\Roaming\npm\node_modules\rxjs-tslint\rxjs-5-to-6-migrate.json" -p "src/tsconfig.app.json" --fix
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\GuptaV\AppData\Roaming\npm\node_modules\rxjs-tslint\node_modules\tslint\lib\linter.js:22:10)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at migrate (C:\Users\GuptaV\AppData\Roaming\npm\node_modules\rxjs-tslint\rxjs-5-to-6-migrate.js:18:34)
    at Object.<anonymous> (C:\Users\GuptaV\AppData\Roaming\npm\node_modules\rxjs-tslint\rxjs-5-to-6-migrate.js:25:14)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)

Please release a fix for this issue

**Comment by mgechev** [comment]
Looks like an environment-specific issue. For further information take a look at the issue tracker for existing solutions.
